"""make product barcode nullable

Revision ID: 6c0994f971c6
Revises: 66bf93f9c0bd
Create Date: 2026-07-21 17:50:35.874678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0994f971c6'
down_revision: Union[str, Sequence[str], None] = '66bf93f9c0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
